version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8000"  # Use 8080 to avoid conflict with ChromaDB
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/network_automation
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./app:/app/app
      - ./frontend:/app/frontend
      - app_data:/app/data
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=network_automation
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  app_data:
